### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by JoeyCreator**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by cpcallen** [comment]
Oh, this would be great—but I tried out the button link just now and didn't get anything resembling a functioning CodeCity instance as a result.

I'm not especially familiar with how [repl.it](https://repl.it) works, but if you can actually get this to work that would be fantastic.  A few notes to help you along the way:

* CodeCity generally depends on node.js, but it ought in principle to be able to run the CodeCity interpreter proper entirely in the browser.  However:
   * Most major browsers now support support [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef), but it will be necessary to update `server/iterable_weakmap.js` and `server/iterable_weakset.js` to use `FinalizationRegistry` instead of `FinalizationGroup` (noting that both the API and the name have changed somewhat).
   * It will also be necessary to provide alternatives to other Node functionality.  The few things we use from the node `util` package should be easy to provide browser alternatives for (I'm sure someone has already written polyfills for these), but it will probably be necessary to disable the networking builtins (`CC.listen` et al.) since there isn't really any way to do those things in a browser.  Except `CC.xhr`; that one will be easy to replace with `XmlHttpReqest`.
* If it's not actually running in a browser but on a repl.it VM, then [the setup instructions](https://github.com/google/CodeCity/blob/master/docs/setup.md) should provide most of what you need to know to be able to get it running.  You'll probably want to replace the existing Google OAuth login service with one connected to repl.it accounts, and I'm not sure how you will handle DNS, TLS certs and so on, but the rest should be straight forward.
* A simpler alternative might be to fire up the `server/repl`](https://github.com/google/CodeCity/blob/master/server/repl) script, which provides a CodeCity-flavoured-JS read/eval/print loop, albeit without checkpointing, etc.

**Comment by JoeyCreator** [comment]
I try to add a link to the run on repl.it button but on the README.md file doesn't look good
Capture d’écran (44)

**Comment by JoeyCreator** [comment]
I have to configure the run button and have enter command.

**Comment by cpcallen** [comment]
I'm going to close this for now, but I would be delighted to re-open it if you can get Code City working on repl.it.

**Pull request closed without merging**
